1.Django/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from mysite.core import views


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('makestudy/', views.makestudy, name='makestudy'),
    path('studygroup/', views.StudyGroupsListView.as_view(), name='studygroup_list'),
    path('studygroup/<int:pk>/', views.studygroup_detail_view, name='studygroup_detail'),
    path('search/', views.searchData, name="searchData"),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

1.Django/mysite/core/models.py
from django.db import models


class StudyGroup(models.Model):
    # 각각의 변수 / 보여지는 단어 로 이루어진 튜플을 가진 dict를 다음과 같이 생성
    field = models.CharField(max_length=80, verbose_name='분야')
    title = models.CharField(max_length=100, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    author = models.CharField(max_length=100, verbose_name='작성자')
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)


class Book(models.Model):
    field = models.CharField(max_length=80)
    title = models.CharField(max_length=80)
    url = models.CharField(max_length=500)
    image_url = models.CharField(max_length=500)

    def __str__(self):
        return self.title

1.Django/mysite/core/forms.py
from django import forms

from .models import StudyGroup


class StudyGroupForm(forms.ModelForm):
    class Meta:
        model = StudyGroup
        fields = ('field','title', 'content', 'author')

1.Django/mysite/core/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from django.contrib import messages
from simplejson import dumps
from .models import StudyGroup, Book


class Home(TemplateView):
    template_name = 'home.html'


# 스터디그룹 리스트 뷰
class StudyGroupsListView(ListView):
    model = StudyGroup
    paginate_by = 10
    template_name = 'studygroup_list.html'  # DEFAULT : <app_label>/<model_name>_list.html
    context_object_name = 'studygroup_list'  # DEFAULT : <app_label>_list

    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        studygroup_list = StudyGroup.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_studygroup_list = studygroup_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            author__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_studygroup_list = studygroup_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_studygroup_list = studygroup_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_studygroup_list = studygroup_list.filter(content__icontains=search_keyword)
                elif search_type == 'author':
                    search_studygroup_list = studygroup_list.filter(author__icontains=search_keyword)

                # if not search_studygroup_list :
                #     messages.error(self.request, '일치하는 검색 결과가 없습니다.')
                return search_studygroup_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return studygroup_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
        context['type'] = search_type
        return context


def studygroup_detail_view(request, pk):
    studygroup = get_object_or_404(StudyGroup, pk=pk)
    # notice = Notice.objects.filter(id=pk)

    context = {
        'studygroup': studygroup,
    }

    studygroup.hits += 1
    studygroup.save()
    return render(request, 'studygroup_detail.html', context)


def makestudy(request):
    if request.method == 'POST':
        StudyGroup.objects.create(
            field=request.POST['field'],
            title=request.POST['title'],
            content=request.POST['content'],
            author=request.POST['author'],
        )
        return redirect('studygroup_list')

    return render(request, 'makestudy.html')

def searchData(request):
    if 'searchwords' in request.GET:
        findthis = request.GET['searchwords']
        print(findthis)
        books = Book.objects.filter(field=findthis).values()
        title = []
        image_url = []
        url = []
        for book in books:
            title.append(book['title'])
            image_url.append(book['image_url'])
            url.append(book['url'])
        context = {
            'title': title,
            'image_url': image_url,
            'bookurl': url,
        }
        json = dumps(context)

        return HttpResponse(json)

1.Django/mysite/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <title>{% block title %}StuOn{% endblock %}</title>
</head>
<body style="background-color: #fff9f9">
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#ffdcdc">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}" style="border-bottom-style: groove; border-color: #ffdcdc; font-weight: bold; color: #666666" >StuOn</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}" style="font-weight: 600; color: #666666 " >홈</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'studygroup_list' %}" style="font-weight: 600; color: #666666 " >스터디 찾기</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'makestudy' %}" style="font-weight: 600; color: #666666 " >스터디 만들기</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body" style="background-color: #fdfdfd; font-weight: 600; color: #666666">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% block js %}{% endblock %}
</body>
</html>

1.Django/mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h4 class="card-title" style="font-weight: bold">언택트시대에 함께 공부할 수 있는 온라인 스터디 모집 공간 </h4>
  <br/>
  <br/>
  <br/>
  <br/>
  <div style="font-size: 20px;">이용법</div>
  <br>
  <div>1. <a href="http://127.0.0.1:8000/studygroup/">스터디 찾기</a>에서 자신에게 맞는 스터디를 찾는다.</div>
  <div>2. 맞는 스터디가 없으면 직접 <a href="http://127.0.0.1:8000/makestudy/">스터디 만들기</a>. </div>

{% endblock %}

1.Django/mysite/templates/makestudy.html
{% extends 'base.html' %}

{% block content %}
  <h2 style="font-weight: bold">스터디 만들기</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div id="div_id_field" class="form-group">
            <label for="id_field" class="col-form-label  requiredField">분야<span class="asteriskField">*</span> </label>
            <div class="">
                <select name="field" class="select form-control" required="" id="id_field">
                    <option value="" selected="">---------</option>
                    <option value="algorithm">Algorithm</option>
                    <option value="python">Python</option>
                    <option value="java">Java</option>
                    <option value="spring">Spring</option>
                    <option value="javascript">Javascript</option>
                    <option value="machinelearning">MachineLearning</option>
                    <option value="deeplearning">DeepLearning</option>
                </select>
            </div>
        </div>
         <div id="div_id_title" class="form-group">
             <label for="id_title" class="col-form-label  requiredField">제목<span class="asteriskField">*</span> </label>
             <div class="">
                 <input type="text" name="title" maxlength="100" class="textinput textInput form-control" required="" id="id_title">
             </div>
         </div>
         <div id="div_id_content" class="form-group">
             <label for="id_content" class="col-form-label  requiredField">내용<span class="asteriskField">*</span> </label>
             <div class="">
                 <textarea name="content" cols="40" rows="10" class="textarea form-control" required="" id="id_content"></textarea>
             </div>
         </div>
         <div id="div_id_author" class="form-group">
             <label for="id_author" class="col-form-label  requiredField">작성자<span class="asteriskField">*</span> </label>
             <div class="">
                 <input type="text" name="author" maxlength="100" class="textinput textInput form-control" required="" id="id_author">
             </div>
         </div>
        <div id="div_id_book" class="form-group">
            <label for="id_book" class="col-form-label  ">추천하는 책</label>
            <div style="display: flex; flex-direction: column; margin: 30px 0 0 0; justify-content: space-around">
                <div id="results"></div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary" style="background-color: #ffecec; border-color: #ffecec; color: #666666; font-weight: bold; box-shadow: 0.5px 1px; ">스터디 만들기</button>
  </form>
{% endblock %}
{% block js %}
{% load static %}
<script src="{% static 'js/register.js' %}"></script>
{% endblock %}

1.Django/mysite/templates/studygroup_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block content %}
<br><br><br>
<div class="container">
    <div class="row-mt-5">
        <div class="col-12">
            <!--본문-->
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header" style="background-color: #ffecec">
                    <strong style="font-size: 18px; color: #666666;">{{ studygroup.title }}</strong>
                    <span style="float:right;">{{ studygroup.registered_date|date:'Y.m.d. H:i' }}</span>
                </div>
                <div class="card-body" style="min-height: 400px; color:black;">
                    <!--작성자, 조회수-->
                    <div>
                        <span style="color: #666666"><i class="fas fa-user-edit" ></i>&nbsp;작성자 : {{ studygroup.author }}</span>
                        <span style="float:right; color: #666666">조회수 : {{ studygroup.hits }}</span>
                    </div>
                    <hr>
                    {% if studygroup.upload_files %}
                    <div class="col-12 text-right">
                        <span style="color: gray;">첨부파일 :&nbsp;</span>
                        <a id="id_uploaded_file" href="{% url 'notice:notice_download' studygroup.id %}" >{{ studygroup.filename|truncatechars:25 }}</a>
                    </div>
                    {% endif %}
                    <!--내용-->
                    <div style="color: #666666">
                        {{ studygroup.content | safe }}
                    </div>
                    {% load disqus_tags %}  <!-- disqus 태그 기능 사용 -->
                    <div>
                        {% disqus_show_comments %}
                    </div>
                </div>
            </div>
            <br>
            <div class="text-right" style="margin-top:-15px;">
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/studygroup/{{ studygroup.id }}/edit/'" style="background-color: #ffecec; border-color: #ffecec; color: #666666; font-weight: bold; box-shadow: 0.5px 1px; ">수정</button>
                <button class="btn btn-sm" id="detail_btn" data-toggle="modal" data-target="#delete_modal" style="background-color: #ffecec; border-color: #ffecec; color: #666666; font-weight: bold; box-shadow: 0.5px 1px; ">삭제</button>
                <!-- <button class="btn btn-md btn-dark" onclick="location.href='/notice/{{ studygroup.id }}/delete/'">삭제</button> -->
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/studygroup/'" style="background-color: #ffecec; border-color: #ffecec; color: #666666; font-weight: bold; box-shadow: 0.5px 1px; ">목록으로</button>
            </div>
        </div>
    </div>

    <div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="font-weight: bold">삭제경고</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>게시글을 삭제하시겠습니까?</p>
                </div>
                <div class="modal-footer">
                    <button onclick="delete_modal()" type="button" class="btn btn-dark" style="background-color: #ffecec; border-color: #ffecec; color: #666666; font-weight: bold; box-shadow: 0.5px 1px; ">삭제하기</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal" style="background-color: #ffecec; border-color: #ffecec; color: #666666; font-weight: bold; box-shadow: 0.5px 1px; ">취소하기</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('img').css('width', '100%');
    });

    function delete_modal() {
        location.replace('/studygroup/{{ studygroup.id }}/delete/');
    }
</script>

{% endblock %}

1.Django/mysite/templates/studygroup_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block content %}
<div class="container">
    <div style="padding-bottom: 20px">
        <div class="col-12">
            <h2 style="font-weight: bold">스터디 찾기</h2>
            {% if q %}
            <h3 style="color: gray; font-weight: 550;"><i class="fas fa-search"></i>&nbsp;'{{ q }}' 검색 결과입니다.</h3>
            {% endif %}
        </div>
    </div>
    <div>
        <table class="table table-sm table-hover">
            <thead style="border-top: 1px solid #dee2e6;">
                <tr class="text-center">
                    <th style="font-weight: bold; font-size: 18px;">번호</th>
                    <th style="font-weight: bold; font-size: 18px;">제목</th>
                    <th style="font-weight: bold; font-size: 18px;">작성자</th>
                    <th style="font-weight: bold; font-size: 18px;">등록일</th>
                    <th style="font-weight: bold; font-size: 18px;">조회수</th>
                </tr>
            </thead>
            <tbody>
                {% if studygroup_list %}
                {% for studygroup in studygroup_list %}
                <tr class="text-center" style="cursor:pointer;" onclick="location.href='/studygroup/{{ studygroup.id }}/'">
                    <td style="font-weight: 400;">{{ studygroup.id }}</td>
                    <td class="text-center" style="width:50%; font-weight: 600;"><a id="studygroup-{{ studygroup.id }}">{{ studygroup.title|truncatechars:30 }}</a></td>
                    <td style="font-weight: 400;">{{ studygroup.author }}</td>
                    <td style="font-weight: 400;">{{ studygroup.registered_date|date:'Y. m. d' }}</td>
                    <td style="font-weight: 400;">{{ studygroup.hits }}</td>
                </tr>
                {% endfor %}
                {% else %}
                    {% if q %}
                    <tr class="text-center">
                        <td style="font-weight: bold; color:gray;" colspan="5">
                            <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
                        </td>
                    </tr>
                    {% else %}
                        <tr class="text-center">
                            <td style="font-weight: bold; color:gray;" colspan="5">
                                <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                            </td>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>
    </div>

    <div style="margin-top: 30px;">
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;" class="form-row">
                    <div class="form-row">
                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title_content">제목+내용</option>
                                <option value="title">제목</option>
                                <option value="content">내용</option>
                                <option value="author">작성자</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <!-- <button class="btn btn-md btn-outline-dark" type="submit">검색</button> -->
                            <button class="btn btn-dark" type="submit" id="search_btn" style="background-color: #ffecec; border-color: #ffecec; color: #666666; font-weight: bold; box-shadow: 0.5px 1px; ">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div class="col-md-offset-6">
            {% if is_paginated %}
            <!-- <ul class="pagination justify-content-center pagination-sm"> -->
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                        tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
    target = window.location.search.split('&')[0].split('=')[1]
    var type = document.getElementsByTagName('option')
    for (var i = 0; i < 5; i++) {
        if (type[i].value === target) {
            type[i].setAttribute('selected', 'selected')
        }
    }
</script>
{% endblock %}